### ISSUE TITLE
[feature]: albility to swap selected line with code on a specific line number

### ISSUE THREAD

**Issue by olpie101** [Fausto95/vscode-swap#3]
As a developer I generally avoid using the mouse/trackpad in order to navigate my editor/IDE having the ability to simply swap the current line with a provide line number would avoid the need to remove my hands from the keyboard.

I propose that a second command be added, possibly named `swap with line (at)` which would enable the ability swap the current line – where the cursor is located – with the code at the provided line number which can be requested from the user.

I would be willing to provided a PR.

**Comment by Fausto95** [comment]
Hi @olpie101 sounds great to me, I'm waiting for your PR.

**Comment by Fausto95** [comment]
@olpie101 this feature has been implemented in #16.
Please let me know if you have any questions and feel free to reopen the issues if needed
